workflows:
  road-cost-workflow:
    name: RoadCost
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: RoadCost API  # Укажите название вашей интеграции App Store Connect в CodeMagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.road.cost
      vars:
        BUNDLE_ID: "com.road.cost"
        XCODE_SCHEME: "RoadCost"
        APP_STORE_APPLE_ID: 6758398062  # Укажите Apple ID вашего приложения в App Store Connect
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Set initial build number
        script: |
          cd $CM_BUILD_DIR
          # Для нового приложения устанавливаем начальный build number
          agvtool new-version -all 1
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "RoadCost.xcodeproj" \
            --scheme "$XCODE_SCHEME"
      - name: Upload to App Store Connect (без отправки на ревью)
        script: |
          # Загружаем IPA в App Store Connect
          echo "Загружаем билд в App Store Connect..."
          app-store-connect publish \
            --path "$CM_BUILD_DIR/build/ios/ipa/*.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
    # Убрана секция publishing, так как не отправляем на модерацию
    # и не нужны email уведомления
