workflows:
  road-cost-workflow:
    name: RoadCost
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: RoadCost API  # Ваша интеграция
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.road.cost
      vars:
        BUNDLE_ID: "com.road.cost"
        XCODE_SCHEME: "RoadCost"
        APP_STORE_APPLE_ID: "6758398062"
        XCODE_PROJECT: "RoadCost.xcodeproj"
      xcode: latest
    scripts:
      # Шаг 1: Установка зависимостей CocoaPods (если есть)
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR
          echo "Проверяем наличие Podfile..."
          if [ -f "Podfile" ]; then
            echo "Устанавливаем CocoaPods зависимости..."
            pod install
          else
            echo "Podfile не найден, пропускаем установку CocoaPods"
          fi
      
      # Шаг 2: Настройка подписания кода
      - name: Set up code signing
        script: |
          cd $CM_BUILD_DIR
          echo "Настраиваем подписание кода..."
          xcode-project use-profiles
          
          # Дополнительная проверка настроек проекта
          echo "Проверяем настройки проекта..."
          xcode-project update-project-settings \
            --bundle-id "$BUNDLE_ID"
      
      # Шаг 3: Установка номера сборки
      - name: Set build number
        script: |
          cd $CM_BUILD_DIR
          echo "Устанавливаем номер сборки..."
          
          # Для первого билда используем 1
          # Если хотите использовать версию из Info.plist, раскомментируйте следующую строку:
          # agvtool new-version -all $(agvtool what-marketing-version -terse1)
          
          agvtool new-version -all 1
          echo "Build number установлен: 1"
      
      # Шаг 4: Сборка и архивация
      - name: Build and archive
        script: |
          cd $CM_BUILD_DIR
          echo "Начинаем сборку проекта..."
          
          # Очистка предыдущей сборки
          echo "Очищаем проект..."
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" || true
          
          # Архивация
          echo "Архивируем проект..."
          xcode-project archive \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
      
      # Шаг 5: Экспорт IPA файла
      - name: Export IPA
        script: |
          cd $CM_BUILD_DIR
          echo "Экспортируем IPA файл..."
          xcode-project export-ipa \
            --archive-path "$CM_BUILD_DIR/build/ios/archive/RoadCost.xcarchive" \
            --method app-store
      
      # Шаг 6: Загрузка в App Store Connect
      - name: Upload to App Store Connect
        script: |
          echo "Загружаем IPA в App Store Connect..."
          
          # Проверяем наличие IPA файла
          IPA_PATH=$(find "$CM_BUILD_DIR/build/ios/ipa" -name "*.ipa" | head -1)
          
          if [ -f "$IPA_PATH" ]; then
            echo "Найден IPA файл: $IPA_PATH"
            echo "Размер файла: $(du -h "$IPA_PATH" | cut -f1)"
            
            # Загружаем в App Store Connect
            app-store-connect publish \
              --path "$IPA_PATH" \
              --submit-for-review false
            
            echo "✅ IPA успешно загружен в App Store Connect!"
          else
            echo "❌ Ошибка: IPA файл не найден!"
            ls -la "$CM_BUILD_DIR/build/ios/ipa/" || true
            exit 1
          fi
    
    # Артефакты сборки
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/xcodebuild.log
